# Generated by Django 3.2.6 on 2021-08-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.TextField()),
                ('graph_binary', models.BinaryField()),
                ('interval', models.IntegerField()),
                ('step', models.IntegerField()),
                ('processing_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
