# Generated by Django 3.2.6 on 2021-08-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_graph_graph_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
    ]
